export const MockData = [
  {
    businessName: "Business Name 1",
    id: "x1",
    address: "Address 1",
    email: "Email 1",
    phoneNumber: "Phone Number 1",
    contactPerson: "Contact Person 1",
    reach: 100,
  },
  {
    businessName: "Business Name 2",
    id: "2",
    address: "Address 2",
    email: "Email 2",
    phoneNumber: "Phone Number 2",
    contactPerson: "Contact Person 2",
    reach: 200,
  },
  {
    businessName: "Business Name 3",
    id: "3",
    address: "Address 3",
    email: "Email 3",
    phoneNumber: "Phone Number 3",
    contactPerson: "Contact Person 3",
    reach: 300,
  },
  {
    businessName: "Business Name 4",
    id: "4",
    address: "Address 4",
    email: "Email 4",
    phoneNumber: "Phone Number 4",
    contactPerson: "Contact Person 4",
    reach: 400,
  },
  {
    businessName: "Business Name 5",
    id: "5",
    address: "Address 5",
    email: "Email 5",
    phoneNumber: "Phone Number 5",
    contactPerson: "Contact Person 5",
    reach: 500,
  },
  {
    businessName: "Business Name 6",
    id: "6",
    address: "Address 6",
    email: "Email 6",
    phoneNumber: "Phone Number 6",
    contactPerson: "Contact Person 6",
    reach: 600,
  },
  {
    businessName: "Business Name 7",
    id: "7",
    address: "Address 7",
    email: "Email 7",
    phoneNumber: "Phone Number 7",
    contactPerson: "Contact Person 7",
    reach: 700,
  },
  {
    businessName: "Business Name 8",
    id: "8",
    address: "Address 8",
    email: "Email 8",
    phoneNumber: "Phone Number 8",
    contactPerson: "Contact Person 8",
    reach: 800,
  },
  {
    businessName: "Business Name 9",
    id: "9",
    address: "Address 9",
    email: "Email 9",
    phoneNumber: "Phone Number 9",
    contactPerson: "Contact Person 9",
    reach: 900,
  },
];
